# -*- coding: utf-8 -*-
"""DataWranglingAutomobile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dHnb-lb2DxVJ24eFDlzIWlM7eIrxL-6O
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score


print("=" * 55)
print("0️⃣  LOADING DATA")
print("=" * 55)

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-SkillsNetwork/labs/Data%20files/auto.csv"

headers = [
    "symboling", "normalized-losses", "make", "fuel-type", "aspiration",
    "num-of-doors", "body-style", "drive-wheels", "engine-location",
    "wheel-base", "length", "width", "height", "curb-weight", "engine-type",
    "num-of-cylinders", "engine-size", "fuel-system", "bore", "stroke",
    "compression-ratio", "horsepower", "peak-rpm", "city-mpg",
    "highway-mpg", "price"
]

df = pd.read_csv(url, names=headers)
df.replace("?", np.nan, inplace=True)
print(f"✅ Loaded: {df.shape[0]} rows × {df.shape[1]} columns")


print("\n" + "=" * 55)
print("1️⃣  MISSING VALUE HANDLING")
print("=" * 55)


numeric_cols = [
    "normalized-losses", "bore", "stroke",
    "horsepower", "peak-rpm", "price",
    "compression-ratio", "engine-size",
    "curb-weight", "wheel-base", "length",
    "width", "height", "city-mpg", "highway-mpg", "symboling"
]
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")


mean_fill_cols = ["normalized-losses", "bore", "stroke", "horsepower", "peak-rpm"]
for col in mean_fill_cols:
    df[col] = df[col].fillna(df[col].mean())


df["num-of-doors"] = df["num-of-doors"].fillna("four")


df = df.dropna(subset=["price"]).reset_index(drop=True)

print(f"✅ Missing values handled. Remaining nulls:\n{df.isnull().sum()[df.isnull().sum() > 0]}")
print(f"✅ Shape after cleaning: {df.shape}")


print("\n" + "=" * 55)
print("2️⃣  DATA TYPE CORRECTION")
print("=" * 55)

df["symboling"] = df["symboling"].astype("int")
df["price"] = df["price"].astype("float")
df["compression-ratio"] = df["compression-ratio"].astype("float")

print("✅ Data types corrected.")
print(df.dtypes)



print("\n" + "=" * 55)
print("3️⃣  STANDARDIZATION: MPG → L/100km")
print("=" * 55)

df["city-L/100km"]    = 235 / df["city-mpg"]
df["highway-L/100km"] = 235 / df["highway-mpg"]

print("✅ MPG converted to L/100km.")
print(df[["city-mpg", "city-L/100km", "highway-mpg", "highway-L/100km"]].head(5))



print("\n" + "=" * 55)
print("4️⃣  NORMALIZATION (0 → 1)")
print("=" * 55)

for col in ["length", "width", "height"]:
    df[f"{col}-normalized"] = (
        (df[col] - df[col].min()) / (df[col].max() - df[col].min())
    )
    print(f"  {col}-normalized → min={df[f'{col}-normalized'].min():.4f}, max={df[f'{col}-normalized'].max():.4f}")

print("✅ Normalization done.")


print("\n" + "=" * 55)
print("5️⃣  OUTLIER DETECTION (IQR)")
print("=" * 55)

def remove_outliers_iqr(dataframe, col):
    Q1 = dataframe[col].quantile(0.25)
    Q3 = dataframe[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    before = len(dataframe)
    dataframe = dataframe[(dataframe[col] >= lower) & (dataframe[col] <= upper)]
    removed = before - len(dataframe)
    print(f"  {col}: removed {removed} outliers (range [{lower:.1f}, {upper:.1f}])")
    return dataframe

df = remove_outliers_iqr(df, "price")
df = remove_outliers_iqr(df, "horsepower")
df = df.reset_index(drop=True)
print(f"✅ Shape after outlier removal: {df.shape}")


print("\n" + "=" * 55)
print("6️⃣  FEATURE ENGINEERING")
print("=" * 55)


df["power-to-weight"] = df["horsepower"] / df["curb-weight"]


df["fuel-efficiency-avg"] = (df["city-L/100km"] + df["highway-L/100km"]) / 2

print("✅ New features created:")
print("  - power-to-weight (horsepower / curb-weight)")
print("  - fuel-efficiency-avg (mean of city + highway L/100km)")
print(df[["power-to-weight", "fuel-efficiency-avg"]].describe())



print("\n" + "=" * 55)
print("7️⃣  BINNING")
print("=" * 55)


bins_hp = np.linspace(df["horsepower"].min(), df["horsepower"].max(), 4)
df["horsepower-binned"] = pd.cut(
    df["horsepower"], bins_hp,
    labels=["Low", "Medium", "High"], include_lowest=True
)


bins_price = np.linspace(df["price"].min(), df["price"].max(), 4)
df["price-binned"] = pd.cut(
    df["price"], bins_price,
    labels=["Low", "Medium", "High"], include_lowest=True
)

print("Horsepower bins:\n", df["horsepower-binned"].value_counts())
print("\nPrice bins:\n", df["price-binned"].value_counts())


print("\n" + "=" * 55)
print("8️⃣  ENCODING")
print("=" * 55)

doors_map = {"two": 2, "four": 4}
df["num-of-doors"] = df["num-of-doors"].map(doors_map)

cylinders_map = {
    "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "eight": 8, "twelve": 12
}
df["num-of-cylinders"] = df["num-of-cylinders"].map(cylinders_map)

dummy_fuel       = pd.get_dummies(df["fuel-type"],   prefix="fuel",       dtype=int)
dummy_aspiration = pd.get_dummies(df["aspiration"],  prefix="aspiration", dtype=int)
dummy_body       = pd.get_dummies(df["body-style"],  prefix="body",       dtype=int)
dummy_drive      = pd.get_dummies(df["drive-wheels"], prefix="drive",     dtype=int)

df = pd.concat([df, dummy_fuel, dummy_aspiration, dummy_body, dummy_drive], axis=1)

print("✅ Ordinal encoding: num-of-doors, num-of-cylinders")
print("✅ Dummy variables: fuel-type, aspiration, body-style, drive-wheels")
print("New dummy columns:", list(dummy_fuel.columns) + list(dummy_aspiration.columns))



print("\n" + "=" * 55)
print("9️⃣  CORRELATION WITH PRICE")
print("=" * 55)

corr_with_price = (
    df.corr(numeric_only=True)["price"]
    .drop("price")
    .sort_values(ascending=False)
)
print(corr_with_price.to_string())



print("\n" + "=" * 55)
print("🔟  VISUALIZATION")
print("=" * 55)

fig, axes = plt.subplots(3, 2, figsize=(14, 16))
fig.suptitle("Automobile Dataset - EDA", fontsize=16, fontweight="bold", y=1.01)


axes[0, 0].scatter(df["engine-size"], df["price"], alpha=0.6, color="steelblue")
axes[0, 0].set_xlabel("Engine Size")
axes[0, 0].set_ylabel("Price ($)")
axes[0, 0].set_title("Engine Size vs Price")

axes[0, 1].scatter(df["horsepower"], df["price"], alpha=0.6, color="tomato")
axes[0, 1].set_xlabel("Horsepower")
axes[0, 1].set_ylabel("Price ($)")
axes[0, 1].set_title("Horsepower vs Price")

axes[1, 0].hist(df["city-L/100km"], bins=15, color="mediumseagreen", edgecolor="black")
axes[1, 0].set_xlabel("City L/100km")
axes[1, 0].set_ylabel("Count")
axes[1, 0].set_title("City Fuel Consumption Distribution")

df.boxplot(column="price", by="body-style", ax=axes[1, 1])
axes[1, 1].set_xlabel("Body Style")
axes[1, 1].set_ylabel("Price ($)")
axes[1, 1].set_title("Price Distribution by Body Style")
plt.sca(axes[1, 1])
plt.xticks(rotation=30)

top_features = corr_with_price.abs().head(10).index.tolist() + ["price"]
corr_matrix = df[top_features].corr()
sns.heatmap(
    corr_matrix, ax=axes[2, 0], annot=True, fmt=".2f",
    cmap="coolwarm", linewidths=0.5, annot_kws={"size": 7}
)
axes[2, 0].set_title("Correlation Heatmap (Top Features vs Price)")
plt.setp(axes[2, 0].get_xticklabels(), rotation=45, ha="right", fontsize=8)
plt.setp(axes[2, 0].get_yticklabels(), fontsize=8)

axes[2, 1].scatter(df["power-to-weight"], df["price"], alpha=0.6, color="darkorchid")
axes[2, 1].set_xlabel("Power-to-Weight Ratio")
axes[2, 1].set_ylabel("Price ($)")
axes[2, 1].set_title("Power-to-Weight Ratio vs Price")

plt.tight_layout()
plt.savefig("automobile_eda.png", dpi=150, bbox_inches="tight")
plt.show()
print("✅ Plots saved to automobile_eda.png")


print("\n" + "=" * 55)
print("1️⃣1️⃣  LINEAR REGRESSION: PREDICT PRICE")
print("=" * 55)

features = [
    "engine-size", "horsepower", "curb-weight",
    "city-L/100km", "highway-L/100km",
    "power-to-weight", "num-of-cylinders",
    "num-of-doors", "wheel-base", "length-normalized",
    "width-normalized", "height-normalized"
]

model_df = df[features + ["price"]].dropna()

X = model_df[features]
y = model_df["price"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = LinearRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print(f"\n📊 Model Performance:")
print(f"   R² Score : {r2:.4f}  (1.0 = perfect)")
print(f"   RMSE     : ${rmse:,.0f}")
print("\n📊 Feature Coefficients:")
coef_df = pd.DataFrame({
    "Feature": features,
    "Coefficient": model.coef_
}).sort_values("Coefficient", ascending=False)
print(coef_df.to_string(index=False))


print("\n" + "=" * 55)
print("1️⃣2️⃣  SAVE CLEANED DATA")
print("=" * 55)

df.to_csv("automobile_cleaned_final.csv", index=False)
print("✅ Saved to automobile_cleaned_final.csv")

print("\n" + "=" * 55)
print("🎉  PROJECT COMPLETE!")
print(f"    Final shape  : {df.shape}")
print(f"    Total columns: {len(df.columns)}")
print("=" * 55)